<?php
 $_COWSAY_COWS = array(
		'apt', 
		'beavis.zen', 'bong', 'bud-frogs', 'bunny',
		'calvin', 'cheese', 'cock', 'cower',
		'daemon', 'default', 'dragon-and-cow', 'dragon', 'duck',
		'elephant', 'elephant-in-snake',
		'eyes',
		'flaming-sheep',
		'ghostbusters', 'gnu',
		'head-in', 'hellokitty',
		'kiss', 'kitty', 'koala', 'kosh',
		'luke-koala',
		'mech-and-cow', 'meow', 'milk', 'moofasa', 'moose', 'mutilated',
		'ren',
		'satanic', 'sheep', 'skeleton', 'small', 'sodomized', 'sodomized-sheep', 'stegosaurus', 'stimpy', 'supermilker', 'surgery', 'suse',
		'telebears', 'three-eyes', 'turkey', 'turtle', 'tux',
		'udder',
		'vader', 'vader-koala',
		'www',
	);
	$_COWSAY_MODES = array(
		'borg' => 'b',
		'dead' => 'd',
		'greedy' => 'g',
		'paranoid' => 'p',
		'stoned' => 's',
		'tired' => 't',
		'wired' => 'w',
		'youthful' => 'y'
	);
	$_COWSAY_MODE_ALIASES = array(
		'b' => 'Cyborg',
		'd' => 'Död',
		'g' => 'Girig',
		'p' => 'Paranoid',
		's' => 'Stenad',
		't' => 'Trött',
		'w' => 'Speedad',
		'y' => 'Ungdomlig'
	);
	$_COWSAY_COW_ALIASES = array(
		'apt' => 'Apt',
		'beavis.zen' => 'Beavis - Zen',
		'bong' => 'Bong',
		'bud-frogs' => 'Grodor',
		'bunny' => 'Kanin',
		'calvin' => 'Kalle',
		'cheese' => 'En ost',
		'cock' => 'Tupp',
		'cower' => 'Gömd ko',
		'daemon' => 'Demon',
		'default' => 'IKEA Standardko',
		'dragon-and-cow' => 'Drake och ko',
		'dragon' => 'Drake',
		'duck' => 'Anka',
		'elephant' => 'Elefant',
		#'elephant-in-snake' => 'Elefant i orm',
		'eyes' => 'Ögon',
		'flaming-sheep' => 'Brinnande får',
		'ghostbusters' => 'Ghostbusters',
		'gnu' => 'Gnu',
		'head-in' => 'Huvudet i ...',
		'hellokitty' => 'Hello kitty',
		'kiss' => 'Grovhångel, hårdporr',
		'kitty' => 'Katt',
		'koala' => 'Koala',
		#'kosh' => '',
		#'luke-koala' => '',
		'mech-and-cow' => 'Robot och ko',
		'meow' => 'Tiger',
		'milk' => 'Mjölkpaket',
		'moofasa' => 'Mufasa',
		'moose' => 'Älg',
		'mutilated' => 'Delad ko',
		'ren' => 'Konstig sak',
		'satanic' => 'Djävulsk kossa',
		'sheep' => 'Får',
		'skeleton' => 'Skelett',
		'small' => 'Liten ko',
		'sodomized' => 'Påsatt ko',
		'sodomized-sheep' => 'Påsatt får',
		'stegosaurus' => 'Stegosaurus',
		'stimpy' => '"Stimpy"',
		'supermilker' => 'Supermjölkmaskin',
		'surgery' => 'Kirurg',
		'suse' => 'Kameleont',
		#'telebears' => '',
		'three-eyes' => 'Lef',
		'turkey' => 'Kalkon',
		'turtle' => 'Sköldpadda',
		'tux' => 'Tux',
		'udder' => 'Konstig ko',
		#'vader' => '',
		#'vader-koala' => '',
		'www' => 'Webbko'
	);
?>